# Generated by Django 2.2.14 on 2022-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='confirmPassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
